# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.TextField(),
        ),
    ]
