# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 22:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20171106_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
