# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='emails_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
