# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_page_model',
        ),
    ]
